#!/bin/bash
# Auto-generated by /work-init
# Purpose: Verify environment for compounding-engineering plugin development

set -e

echo "🚀 Initializing Claude agent environment..."
echo ""

# Verify we're in the right directory
PLUGIN_JSON=".claude-plugin/plugin.json"
if [ ! -f "$PLUGIN_JSON" ]; then
    echo "❌ Error: Not in plugin directory (missing $PLUGIN_JSON)"
    exit 1
fi

# Extract and display plugin info
echo "📦 Plugin Info:"
echo "   Name: $(cat $PLUGIN_JSON | grep -o '"name"[[:space:]]*:[[:space:]]*"[^"]*"' | head -1 | cut -d'"' -f4)"
echo "   Version: $(cat $PLUGIN_JSON | grep -o '"version"[[:space:]]*:[[:space:]]*"[^"]*"' | head -1 | cut -d'"' -f4)"
echo ""

# Count components
echo "📊 Component Counts:"
AGENT_COUNT=$(ls agents/*/*.md 2>/dev/null | wc -l | tr -d ' ')
COMMAND_COUNT=$(find commands -name "*.md" -type f 2>/dev/null | wc -l | tr -d ' ')
SKILL_COUNT=$(ls -d skills/*/ 2>/dev/null | wc -l | tr -d ' ')
echo "   Agents: $AGENT_COUNT"
echo "   Commands: $COMMAND_COUNT"
echo "   Skills: $SKILL_COUNT"
echo ""

# Check git status
echo "📝 Git Status:"
if git diff --quiet 2>/dev/null; then
    echo "   Working tree is clean"
else
    echo "   Uncommitted changes detected"
    git status --short
fi
echo ""

# Verify progress.txt exists
if [ -f ".claude/progress.txt" ]; then
    echo "✅ progress.txt ready for session logging"
else
    echo "⚠️  progress.txt not found - run /work-init"
fi

echo ""
echo "✅ Environment ready for development"
echo ""
echo "Quick commands:"
echo "  /plan <feature>   - Create a new task plan"
echo "  /work <plan>      - Execute a work plan"
echo "  /review           - Review code changes"
echo "  /compound         - Document solved problems"
